### ISSUE TITLE
About Dynamic gophermaps The shell cannot be identified

### ISSUE THREAD

**Issue by Nial4** [michael-lazar/hn-gopher#1]
"i" and "=echo"  is visible in index page. I try to chmod +x gophermap,but it seems that not useful :(

**Comment by Nial4** [comment]
postscript: Debian7  x64  3.2.96-2  GNU/Linux

**Comment by michael-lazar** [comment]
How did you install it? Are you using the version of gophernicis that’s bundled with with repository? I made some changes to the gophernicus source code, specifically around how ‘’i’’ is rendered, that might make my gophermaps incompatible with other versions of gophernicus

**Comment by Nial4** [comment]
I got it, I forgot to kill pygopherd process, the pygopherd does not support dynamic gophermaps, but have new error, show " Error: Access denied !" when run "/usr/sbin/in.gophernicus" . Have you Encountered ? Thank you very much.

**Comment by Nial4** [comment]
I "rm -f /var/gopher/ reinstall gophernicus and inetd service ,amazing-.- It's normal runing. My English is not so good, spent a week on this , I love Gopher !, thanks for your help !  I'm sorry if I troubled you.

**Comment by michael-lazar** [comment]
I'm glad that you figured it out! I look forward to seeing your gopher site soon :)
